[package]
name = "clay"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A lightweight, 2D game engine for game jams!"
repository = "https://github.com/ThiccTheo/clay"

[dependencies]
ggez = "0.9.3"
hashbrown = "0.14.5"
